### ISSUE TITLE
Support for LPUTF8Str

### ISSUE THREAD

**Issue by bddckr** [Firwood-Software/AdvancedDLSupport#96]
**Is your feature request related to a problem? Please describe.**
I'm trying to do some interop with a Go library that exports some functions as C functions.

```go
package main

import "C"

func main() {}

//export Verify
func Verify() *C.char {
    return C.CString("Test! 🎉")
}
```
[`cgo`](https://golang.org/cmd/cgo/) outputs the following function definition for that:
```c
extern char* Verify();
```

**Describe the solution you'd like**
This is what I would like to use:
```c#
internal interface IVerify : IDisposable
{
    [return: MarshalAs(UnmanagedType.LPUTF8Str)]
    public string Verify();
}
```
However, I'm getting an exception on the activation of this interface instead:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The unmanaged type wasn't a recognized string type. (Parameter 'unmanagedType')
  Source=AdvancedDLSupport
  StackTrace:
   at AdvancedDLSupport.ImplementationGenerators.StringMarshallingWrapper.SelectUnmanagedToManagedTransformationMethod(UnmanagedType unmanagedType)
   at AdvancedDLSupport.ImplementationGenerators.StringMarshallingWrapper.EmitEpilogue(ILGenerator il, PipelineWorkUnit`1 workUnit)
   at AdvancedDLSupport.ImplementationGenerators.CallWrapperBase.<GenerateImplementation>d__2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AdvancedDLSupport.Pipeline.ImplementationPipeline.ConsumeDefinitions[T](IEnumerable`1 definitions, IReadOnlyList`1 pipeline)
   at AdvancedDLSupport.NativeLibraryBuilder.ConstructMethods(ImplementationPipeline pipeline, Type classType, Type[] interfaceTypes)
   at AdvancedDLSupport.NativeLibraryBuilder.GenerateInterfaceImplementationType(Type classType, Type[] interfaceTypes)
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateClass(String libraryPath, Type baseClassType, Type[] interfaceTypes)
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateClass[TClass,TInterface](String libraryPath)
   at AdvancedDLSupport.NativeLibraryBuilder.ActivateInterface[TInterface](String libraryPath)
   at TestApp.Program.Main() in C:\Projects\TestApp\TestApp\Program.cs:line 38
```

**Describe alternatives you've considered**
I'm currently using this instead:
```c#
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
internal readonly struct NativeUtf8String
{
    private readonly IntPtr String;

    public static explicit operator string(NativeUtf8String native) =>
        Marshal.PtrToStringUTF8(native.String);
}
```

**Additional context**
I believe `StringMarshallingWrapper` needs to be updated to support `LPUTF8Str`, however I'm wondering whether there are any runtime-specific details I'm not aware of.

Also: Is there a way to add support for `LPUTF8Str` without adjusting `StringMarshallingWrapper`, in case direct support is not of interest for this library?

**Comment by Nihlus** [comment]
Hi! 

Thank you for your report :) The reason this is not in the library at the moment is because the relevant marshalling function was only added in .NET Standard 2.1, and ADL targets 2.0. I'll investigate if I can work around the issue some other way, though. 

What you can do is create and inject your own marshalling stage - effectively, your own `StringMarshallingWrapper` that deals with this specific case and nothing else.

**Comment by bddckr** [comment]
>the relevant marshalling function was only added in .NET Standard 2.1

Oh whoops! I didn't realize 😅

>What you can do is create and inject your own marshalling stage

That sounds reasonable! I looked into this already and got stuck at `ImplementationPipeline`. I have no idea how I can get to an instance of it to call its `InjectMethodStages` method. The only instance creation I can find is in `GenerateInterfaceImplementationType`, which is private.

**Comment by Nihlus** [comment]
Ah darn, sorry about that - it looks like I haven't exposed that API through the builder yet. I was sure I had.

Anyway, I figured out a relatively easy way to support this on runtimes where UTF-8 string marshalling is available. Version 3.2.0 should hit nuget soon with the fix in place :)

**Comment by bddckr** [comment]
I just confirmed it works now! Thanks a lot, that was fast 🚀

**Comment by Nihlus** [comment]
Great!
